blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
app_name = "blog"

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name='delete'),
]

core/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomeView.as_view(), name='Home'),
    path('blog/',include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

    def __str__(self):
        txt = '{0}'
        return txt.format(self.title)
    

blog/forms.py
from django import forms
from django.forms import fields

from .models import Post

class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'content')

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

class BlogListView(View):

    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts':posts
        }
        return render(request, 'blog_list.html', context)

class BlogCreateView(View):
    
    def get(self, request, *args, **kwargs):
        form = PostCreateForm
        context = {
            'form':form
        }
        return render(request, 'blog_create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, create = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')
        context = {

        }
        return render(request, 'blog_create.html', context)

class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context = {
            'post':post
        }
        return render(request, 'blog_detail.html', context)

class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})

class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):

    def get(self, request, *args, **kwargs):
        context = {

        }
        return render(request, 'index.html', context)

templates/blog_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Blog</title>
</head>

<body>
    <form method="POST">
        {% csrf_token %} title {{form.title}}
        <br> content {{form.content}}
        <button type="submit">Submit</button>
    </form>
</body>

</html>

templates/blog_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Blog</title>
</head>

<body>
    <form method="POST">
        {% csrf_token %} Are you sure ? {{form}}
        <button type="submit">Delete</button>
    </form>
    <button><a href="{% url 'blog:home' %}">Cancelar</a></button>
</body>

</html>

templates/blog_detail.html
{{post.title}}
<br> {{post.content}}

templates/blog_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Blogs</title>
</head>

<body>
    <h2>Blog List</h2>
    <br> {% for post in posts %}
    <li>
        <a href="{% url 'blog:detail' post.id %}">{{post.title}}</a> - <a href="{% url 'blog:update' post.id %}">Editar</a> - <a href="{% url 'blog:delete' post.id %}">Eliminar</a></li>
    {% endfor %}
    <br>
    <a href="{% url 'blog:create' %}">Crear</a>
</body>

</html>

templates/blog_update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Blog</title>
</head>

<body>
    <form method="POST">
        {% csrf_token %} title {{form.title}}
        <br> content {{form.content}}
        <button type="submit">Save</button>
    </form>
    <button><a href="{% url 'blog:home' %}">Regresar</a></button>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Hola !</h1>
    <h2>Vista mi <a href="{% url 'blog:home' %}">blog aqui</a></h2>
</body>

</html>